### ISSUE TITLE
Method for Visibility (not Shutdown)

### ISSUE THREAD

**Issue by marchofreason** [johnnynotsolucky/vue-intercom#10]
Using this Wrapper for our Intercom on our VueJS App as it makes life much easier.
Thank you for all your work on this.

**What I'm trying to do:**
Make the intercom messenger invisible (hidden) on a specific page where I need the real estate and the messenger location gets in the way

**What I've tried**
Tried to use the this.$intercom.shutdown() in one of my init() methods when the page loads and this works but then the intercom messenger is no longer booted. 
I still need it active in the event of messages being pushed through or support required. 

this.$intercom.hide() does not affect the visibility of the messenger

Would you be able to help ?

**Comment by johnnynotsolucky** [comment]
@marchofreason I'm glad its helping you out :-)

You should be able to make use of the `hide_default_launcher` Intercom property.

For example, in App.vue, you can mount it and set it to be displayed:
```javascript
  mounted() {
    this.$intercom.boot({
      user_id: 123456,
      name: '...',
      email: '...',
      hideDefaultLauncher: false,
    });
  },
```

and on specific routes, update to hide the widget:

```javascript
  mounted() {
    this.$intercom.update({
      hideDefaultLauncher: true,
    });
  },
  beforeDestroy() {
    // Show the launcher again
    this.$intercom.update({
      hideDefaultLauncher: false,
    });
  }
```

**Comment by johnnynotsolucky** [comment]
Closing this as resolved. Please reopen if the solution isn’t working for you.
