### ISSUE TITLE
Shutdown doesn't delete cookies?

### ISSUE THREAD

**Issue by benwrigley** [johnnynotsolucky/vue-intercom#11]
Hi There,

It seems that calling the `shutdown()` method doesn't actually delete cookies and so the user remains logged in.

**Comment by johnnynotsolucky** [comment]
@benwrigley the methods available only wrap the Intercom JS API. The shutdown method is calling `window.Intercom('shutdown')`. You can test if it is working by calling the Intercom API directly from your browsers console.
