### ISSUE TITLE
Boot takes ~200ms on pageload, can it be deferred?

### ISSUE THREAD

**Issue by d1manson** [johnnynotsolucky/vue-intercom#13]
You mention in another issue that you don't need boot to complete before using the other methods, but as far as I understand from your comment you should at least kick off the boot before calling the other methods:

https://github.com/johnnynotsolucky/vue-intercom/issues/2#issuecomment-342275826

It would be nice to remove that restriction. Or maybe have an additional option in boot so that it only starts up on demand.

**Comment by johnnynotsolucky** [comment]
Hi @d1manson, apologies for the delay getting back to you. It should be trivial to add that functionality, however, I'd prefer to keep the API as close to Intercom's as possible. If there was a bug with the Intercom script, for example, it would be a lot easier for users to trace the function calls.
