### ISSUE TITLE
Email in $intercom.boot() don't work

### ISSUE THREAD

**Issue by anykarolyne** [johnnynotsolucky/vue-intercom#6]
Just name works, when I added email don't work. 

My code:

`        
          
          this.$intercom.boot({
                      
                     name: 'karol',

                     email: 'karol@gmail.com',

                     custom_launcher_selector: '#intercom_custom_launcher_selector'
          })`

Version of vue-intercom: "^1.0.12",

**Comment by johnnynotsolucky** [comment]
Hi @anykarolyne, does it not load the launcher or does is not track the user in Intercom?

**Comment by anykarolyne** [comment]
Doesn't load the launcher

**Comment by johnnynotsolucky** [comment]
It is possible that the `#intercom_custom_launcher_selector` isn't available when the Intercom component is booted. Could you post some code which replicates the issue?
