### ISSUE TITLE
intercom messenger alignment gets reset unless they are re-sent on each update

### ISSUE THREAD

**Issue by hmexx** [johnnynotsolucky/vue-intercom#7]
is this how intercom works?
```
     Vue.prototype.$intercom.boot({
      alignment: "left",
      horizontal_padding: 20,
      vertical_padding: 20
    });

    Vue.prototype.$intercom.update({
        user_id: store.getters.uid,
        email: s.user.info.email,
        name: s.user.info.firstName,
        iscoach: store.getters.isCoach,
        istrainee: store.getters.isTrainee,
        isonboarded: store.getters.isOnboarded
    });
```

The second call will reset the alignment to its usual position. This can be resolved by resending the aligntment metadata each time, but I'm wondering if it's a vue-intercom bug or not. 

Thanks the great component!

**Comment by johnnynotsolucky** [comment]
This would most likely be the Intercom widgets behaviour. vue-intercom acts purely as a proxy to window.Intercom so anything you pass to one of the functions in vue-intercom is passed without modification to window.Intercom()

Thanks for reporting this and I’m happy you’re finding it useful :-)
