### ISSUE TITLE
Support for user_hash User Verification

### ISSUE THREAD

**Issue by matthew-kerle** [johnnynotsolucky/vue-intercom#8]
Do you support `user_hash` for user verification within Intercom? I tried passing it in the instance options with `appId` and Intercom is not receiving it. Can we get support for this?

**Comment by johnnynotsolucky** [comment]
You should be able to get it working by passing it through in the `boot` function:

```javascript
this.$intercom.boot({
  user_hash: this.userHash,
  name: this.name,
  email: this.email,
});
```
