### ISSUE TITLE
Scrolling issue iOS 11

### ISSUE THREAD

**Issue by ricardobanegas** [johnnynotsolucky/vue-intercom#9]
I found an issue on __iPhone 7__ running __iOS 11.3__

After pressing on "Send a message" the scroller scroll down to the input, as on screenshot.

### Repro steps:

1. Installed vue-intercom
2. Intercom in ready() state
3. Open chat bubble manually
4. Click on "Send a message"
5. Scrolls to top.

```javascript
    watch: {
        '$intercom.ready': () => {
            this.$intercom.show()
        }
    },
    mounted () {
        this.$intercom.boot({
            application: 'web'
        })
    }
```

![img_e2c62e2e01a9-1](https://user-images.githubusercontent.com/943250/39329596-1c670bd0-499f-11e8-9062-b8f1f86f6f89.jpeg)

Thanks in advance, and for a great wrapper to intercom!

**Comment by johnnynotsolucky** [comment]
Hi @ricardobanegas, I think the behaviour you're referring to is intended behaviour with the Intercom widget itself: 

![example](https://user-images.githubusercontent.com/4161106/39400374-4344bd60-4b2f-11e8-952e-9f4b45c67183.gif)

**Comment by ricardobanegas** [comment]
Hello again, sorry for the late reply.

As you can see, the widget works differently on the site I'm developing and intercom.com. 

![may-02-2018 5-02-21 pm](https://user-images.githubusercontent.com/943250/39531068-a9137e12-4e2a-11e8-8b07-e2c74d73cf40.gif)

**Comment by johnnynotsolucky** [comment]
Oooh I see. I'm on iOS 11 and I can't actually get the Intercom widget to load up even from intercom.com :-/

vue-intercom only loads the Intercom script and proxies calls to the widget's functions, it shouldn't be affecting any styling with the widget.

Can you try out this codesandbox setup and see if the issue persists there: https://codesandbox.io/s/3vkzyy1r6 and here's the view on its own: https://3vkzyy1r6.codesandbox.io/

Are you using an emulator for that recording?

**Comment by ricardobanegas** [comment]
Found it! 

Using [Bulma](https://github.com/jgthms/bulma) only for reseters + columns in my project. Dicovered that these two lines (`overflow-x`, `overflow-y`) on `html {}` caused this issue.

https://github.com/jgthms/bulma/blob/master/sass/base/generic.sass#L28

Reseting this to `overflow: visible` solved the issue.

Thanks for the help!

**Comment by johnnynotsolucky** [comment]
Awesome! I'm glad you found the issue :-D
